// Code generated by sdi. DO NOT EDIT.
package order

// Deps returns a list of dependencies required by Service.
func (r *Service) Deps() []any {
	return []any{
		(*OrderRepository)(nil),
	}
}

// Inject sets the dependencies for Service.
func (r *Service) Inject(args []any) {
	for _, arg := range args {
		switch v := arg.(type) {
		case OrderRepository:
			r.repo = v
		}
	}
}
