// Code generated by obsgen. DO NOT EDIT.
package item

import (
	"context"
	"fmt"
	"github.com/omcrgnt/demo/internal/domain/model"
	"github.com/prometheus/client_golang/prometheus"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func (r *Service) Observe() any {
	return newObserveService(r)
}

type observeService struct {
	*Service
	label string
}

func newObserveService(base *Service) *observeService {
	o := &observeService{Service: base}
	if l, ok := any(base).(interface{ Label() string }); ok {
		o.label = l.Label()
	}
	return o
}

func (o *observeService) Deps() []any {
	return o.Service.Deps()
}

func (o *observeService) Inject(args []any) {
	o.Service.Inject(args)
}

func (o *observeService) Label() string {
	return o.Service.Label()
}

func (o *observeService) RegisterMetrics(reg *prometheus.Registry) error {
	return o.Service.RegisterMetrics(reg)
}

func (o *observeService) List(ctx context.Context) ([]model.Item, error) {
	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"List")
	defer span.End()
	res0, err := o.Service.List(ctx)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return res0, fmt.Errorf("[%s] List: %w", o.label, err)
	}
	return res0, err
}

func (o *observeService) Get(ctx context.Context, id string) (model.Item, error) {
	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"Get")
	defer span.End()
	res0, err := o.Service.Get(ctx, id)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return res0, fmt.Errorf("[%s] Get: %w", o.label, err)
	}
	return res0, err
}

func (o *observeService) Create(ctx context.Context, title string) (model.Item, error) {
	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"Create")
	defer span.End()
	res0, err := o.Service.Create(ctx, title)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return res0, fmt.Errorf("[%s] Create: %w", o.label, err)
	}
	return res0, err
}

func (o *observeService) Update(ctx context.Context, id string, title string) (model.Item, error) {
	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"Update")
	defer span.End()
	res0, err := o.Service.Update(ctx, id, title)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return res0, fmt.Errorf("[%s] Update: %w", o.label, err)
	}
	return res0, err
}

func (o *observeService) Delete(ctx context.Context, id string) error {
	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"Delete")
	defer span.End()
	err := o.Service.Delete(ctx, id)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return fmt.Errorf("[%s] Delete: %w", o.label, err)
	}
	return err
}
